name = "marketdatafetch"
main = "marketdata/worker.js"
compatibility_date = "2025-10-02"
account_id = "fe06da04ece4e57f92d701596d6afec9"
workers_dev = true

[triggers]
crons = ["0 21 * * mon-fri"] 

[[d1_databases]]
binding = "DB"
database_name = "stock_data_history"
database_id = "139372d8-73fd-46b7-b118-cccb247d19e7"

[vars]
ORIGIN = "https://m-zhang.me"
WRITE_TO_D1 = "true"

