name = "marketdatafetch"
main = "marketdata/worker.js"
compatibility_date = "2025-09-01"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
URL [web:51]

[vars]
ORIGIN = "https://m-zhang.me"
TTL = "300"
