name = "marketdatafetch"
main = "marketdata/worker.js"
compatibility_date = "2025-09-01"
account_id = "fe06da04ece4e57f92d701596d6afec9"
workers_dev = true

[vars]
ORIGIN = "https://m-zhang.me"
TTL = "300"

[observability]
enabled = true

[triggers]
crons = ["0 21 * * mon-fri"]
